ACVTOOL_PATH = r"C:\projects\droidmod-smali-modifier"
ACVTOOL_PYTHON = r"c:\Python27\python.exe"
APK_REPOSITORY = r"C:\fdroid_results"
ACVTOOL_RESULTS = r"C:\acvtool_results"
ACVTOOL_WD = r"C:\projects\droidmod-smali-modifier\smiler\acvtool_working_dir"